hash-format = "sha256"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "32dc5f1d73b05e70f3fc5a18f58c5d81a095484a0f93a1da6d1883966ff4e296"

[[files]]
file = "config/badoptimizations.txt"
hash = "2917a8f8112e36e27b240bdbe0e6987c5e8b0964595ed42ca2fbe1b16350df71"

[[files]]
file = "config/c2me.toml"
hash = "a72fb311d1a56ac2b4c069b5225f8c7d09302fe4250ee3a842145ae271a2d5a2"

[[files]]
file = "config/entityculling.json"
hash = "6bb3b6b65f728d5c3d06dd986b85d21370e3b78a30629b7a1ab7a0a46e033768"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "5287b32edcac91203df51c442436bab5ed42e3add3303406f9cdd832a912249a"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/immediatelyfast.json"
hash = "52676c32fa8db48a4010253bb35cc132c1cb57c68eb9c40643713aacdd0f2ce3"

[[files]]
file = "config/lithium.properties"
hash = "928fdb1e604e394de7389a4b7a7f230fe6863a468e1839bee22d80652ea0d31f"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "d8f165e35901ad5409ef7e9ae4f1be80d3a4f4d4f5a7ce0f1b2062fd4a4b9c84"

[[files]]
file = "config/moreculling.toml"
hash = "ad9502638dfc64191c82e28efeede417bd4ab32b6276e60117bc978e41b936bd"

[[files]]
file = "config/sodium-options.json"
hash = "77e47f82d7d77e20d0ab0d2f6a9b15b8a2aa18c833965a6d92375f28588e9cca"

[[files]]
file = "config/threadtweak.json"
hash = "b4c1cc5fc213225d64e685a3b632092e909386ab41bd9925f9cf7efd53d1ad46"

[[files]]
file = "config/vmp.properties"
hash = "15eec0092ca5c54f97fc46953311e20e63a5eb6bca4672bfec9dae63f61cc456"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b72d00d529ec694ae354b73f6b36d4ec2b830c60c05cc31f46d00ac7ddf8a26b"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a8f073ab0640d9e501fe3fc95d282306000fd6eab3186fd682269c0d0913b307"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9e7bacd24307639764f3b74ae35a562b6becf2701637b816de0eaae15ab714c0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9a74f9345a91af6a0e2c1975e1dd1d26cfcae6fb072a3a0d68fd9de110ab6327"
metafile = true

[[files]]
file = "mods/minimotd.pw.toml"
hash = "072589c2436b05489b0e8271d7b2bd51b8e47de9b319541025cd49d412cc6cb1"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "67116d1cf5d38dfd27aded9d675afcc625d720a4d457660ff82db760934d9f4d"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0544fefc6f04f2b408b2c6b4dd3e4bf7d0a4048f1fad6ddf63357549d7446165"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "cd25851cbdaad2dd1957a8086ce54aa4bd3c45be75e1ba49168a54fafbd87898"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "7154c5bc0a407fa33240c0900db06bd4be0838316f06e3e1c1b27ee8856b0fe5"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9ff1a261860fcb16a7c7f124d738abcdfc1297363412d237540685003ff04d6b"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9d340481c374a20067d1748c1a4991626bce9d7812f0bdb96072cd7a15d35462"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "147236c9b21df25b05d0715f21faf8c9b89dfa7af9d157c532f8e94887d47a65"
metafile = true

[[files]]
file = "options.txt"
hash = "9c72c06157d45897bd7a0c60c1713ad3d46d7b25e8a1c0d0e841a9af0f47cb30"
