hash-format = "sha256"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "501acdaa439603e3a002cd2da5aad794ff9f39b2c75270bfab5779e2d7c6e0d8"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "d7df52986724052636885af06a28bbf11eb919fc58b7dafdffdf22d6805d4eaf"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a216e613b5ada8a83972394c8b52331388f6d3e41187a04c3bced3f1752bea70"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7af4476d6dee900025bd949e921bceeed2166137798e397c06f21a7e2ff26bbe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "70ef4c56ac7d929c6d7b86b0922450df1fdd4bd7042a77f5b57ec73e13701466"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "cf0b694687c823b69ebb1cc78f72fdd83cc86c106354b30a7c157f4ca534c9ef"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e10c94949bb58b8cfa9993a9f60c9283d5858d4d55fc450dbff2953644f45047"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6d8c2cffdc5db64f6134d6427dd0ac938ec659a56ba8f7655889bfd8b3368239"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "ba94fd9dd7d5148b511c24460a281143c3a5d02b859e66732f6121aee6625f0d"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "54dd8b88e92786d96c2487b7d6a473fbb7cd4576cec3a543788cfab327ffd623"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "fcb2b48e962361d11130754a8e2d524a5e5fb4025e18f0135096a95aabc5cb24"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1745f4ec1732e16be5f2c88780a66ca2a94c76c06c5e862db0b2c6cf63b16a47"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "0a62d4e9dab1aa7186540e633f2fd94012e8300f7afece66768efdb3508f3ede"
metafile = true
