hash-format = "sha256"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "32dc5f1d73b05e70f3fc5a18f58c5d81a095484a0f93a1da6d1883966ff4e296"

[[files]]
file = "config/badoptimizations.txt"
hash = "2917a8f8112e36e27b240bdbe0e6987c5e8b0964595ed42ca2fbe1b16350df71"

[[files]]
file = "config/c2me.toml"
hash = "a72fb311d1a56ac2b4c069b5225f8c7d09302fe4250ee3a842145ae271a2d5a2"

[[files]]
file = "config/entityculling.json"
hash = "6bb3b6b65f728d5c3d06dd986b85d21370e3b78a30629b7a1ab7a0a46e033768"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "5287b32edcac91203df51c442436bab5ed42e3add3303406f9cdd832a912249a"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/immediatelyfast.json"
hash = "52676c32fa8db48a4010253bb35cc132c1cb57c68eb9c40643713aacdd0f2ce3"

[[files]]
file = "config/lithium.properties"
hash = "928fdb1e604e394de7389a4b7a7f230fe6863a468e1839bee22d80652ea0d31f"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "d8f165e35901ad5409ef7e9ae4f1be80d3a4f4d4f5a7ce0f1b2062fd4a4b9c84"

[[files]]
file = "config/moreculling.toml"
hash = "ad9502638dfc64191c82e28efeede417bd4ab32b6276e60117bc978e41b936bd"

[[files]]
file = "config/sodium-options.json"
hash = "77e47f82d7d77e20d0ab0d2f6a9b15b8a2aa18c833965a6d92375f28588e9cca"

[[files]]
file = "config/threadtweak.json"
hash = "b4c1cc5fc213225d64e685a3b632092e909386ab41bd9925f9cf7efd53d1ad46"

[[files]]
file = "config/vmp.properties"
hash = "15eec0092ca5c54f97fc46953311e20e63a5eb6bca4672bfec9dae63f61cc456"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "501acdaa439603e3a002cd2da5aad794ff9f39b2c75270bfab5779e2d7c6e0d8"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "d7df52986724052636885af06a28bbf11eb919fc58b7dafdffdf22d6805d4eaf"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a216e613b5ada8a83972394c8b52331388f6d3e41187a04c3bced3f1752bea70"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7af4476d6dee900025bd949e921bceeed2166137798e397c06f21a7e2ff26bbe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "70ef4c56ac7d929c6d7b86b0922450df1fdd4bd7042a77f5b57ec73e13701466"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "cf0b694687c823b69ebb1cc78f72fdd83cc86c106354b30a7c157f4ca534c9ef"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e10c94949bb58b8cfa9993a9f60c9283d5858d4d55fc450dbff2953644f45047"
metafile = true

[[files]]
file = "mods/modernfix-fabric-5.20.4-beta.54+mc1.21.8.c05a.jar"
hash = "09db495c7031be8d5e34242cb188bf569469eba5a23fa70bf66a4c07d7f98a07"

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6d8c2cffdc5db64f6134d6427dd0ac938ec659a56ba8f7655889bfd8b3368239"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "ba94fd9dd7d5148b511c24460a281143c3a5d02b859e66732f6121aee6625f0d"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "54dd8b88e92786d96c2487b7d6a473fbb7cd4576cec3a543788cfab327ffd623"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "fcb2b48e962361d11130754a8e2d524a5e5fb4025e18f0135096a95aabc5cb24"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1745f4ec1732e16be5f2c88780a66ca2a94c76c06c5e862db0b2c6cf63b16a47"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "0a62d4e9dab1aa7186540e633f2fd94012e8300f7afece66768efdb3508f3ede"
metafile = true

[[files]]
file = "options.txt"
hash = "9c72c06157d45897bd7a0c60c1713ad3d46d7b25e8a1c0d0e841a9af0f47cb30"
