name = "superhipermegacoolmodpackwowamazing2000finalv2_FINAL"
author = "boredvico"
version = "0.1.69"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f4ec1786328afdac0f8e9db526e7cb550bd33312c5156a3292dabf675807b4f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
