name = "superhipermegacoolmodpackwowamazing2000finalv2_FINAL"
author = "boredvico"
version = "0.1.69"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46914de3a144352da5b70052694f13a470f88b41100371901481abd6619cc670"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
